#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Sprawdzam formatowanie Scalafmt..."

./format.sh
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "Formatowanie niepoprawne."
  exit 1
else
  echo "Formatowanie OK."
fi
